/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tomsopt_kernel_Matern52 */

#ifndef _Included_tomsopt_kernel_Matern52
#define _Included_tomsopt_kernel_Matern52
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tomsopt_kernel_Matern52
 * Method:    applyNative
 * Signature: ([DI[DII)D
 */
JNIEXPORT jdouble JNICALL Java_tomsopt_kernel_Matern52_applyNative
  (JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
