/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tomsopt_kernel_KernelUpdaterNative */

#ifndef _Included_tomsopt_kernel_KernelUpdaterNative
#define _Included_tomsopt_kernel_KernelUpdaterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tomsopt_kernel_KernelUpdaterNative
 * Method:    _nativeUpdate
 * Signature: ([DII[DII[DIIIDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tomsopt_kernel_KernelUpdaterNative__1nativeUpdate
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jint, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
